SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCOPIASEGURANCA;
CREATE DATABASE DBCOPIASEGURANCA;
USE DBCOPIASEGURANCA;

CREATE TABLE CLIENTE(

	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, DT_NASCIMENTO DATE
	, CPF CHAR(11)
	, CIDADE VARCHAR(100)
	, ESTADO CHAR(2)

);

CREATE TABLE BACKUP_CLIENTE(
	IDBACKUP INT NOT NULL AUTO_INCREMENT,
    IDCLIENTE INT NOT NULL
	, ANTES_NOME VARCHAR(100)
    , DEPOIS_NOME VARCHAR(100)
	, ANTES_DT_NASCIMENTO DATE
    , DEPOIS_DT_NASCIMENTO DATE
	, ANTES_CPF CHAR(11)
    , DEPOIS_CPF CHAR(11)
	, ANTES_CIDADE VARCHAR(100)
    , DEPOIS_CIDADE VARCHAR(100)
	, ANTES_ESTADO CHAR(2)
    , DEPOIS_ESTADO CHAR(2)
    , TIPO VARCHAR(20)
    , DATA_MODIFY DATETIME
    ,PRIMARY KEY (IDBACKUP)
);


DELIMITER $$ 
CREATE TRIGGER TR_AU_CLIENTE AFTER UPDATE ON CLIENTE FOR EACH ROW 
BEGIN
	INSERT INTO BACKUP_CLIENTE VALUES(DEFAULT,OLD.IDCLIENTE,OLD.NOME,NEW.NOME,OLD.DT_NASCIMENTO,NEW.DT_NASCIMENTO,OLD.CPF,NEW.CPF,OLD.CIDADE,NEW.CIDADE,OLD.ESTADO,NEW.ESTADO,'ALTERADO', NOW() );
END $$
CREATE TRIGGER TR_AD_CLIENTE AFTER DELETE ON CLIENTE FOR EACH ROW 
BEGIN
	INSERT INTO BACKUP_CLIENTE VALUES(DEFAULT,OLD.IDCLIENTE,OLD.NOME,'',OLD.DT_NASCIMENTO,NULL,OLD.CPF,'',OLD.CIDADE,'',OLD.ESTADO,'','DELETADO', NOW() );
END $$
CREATE TRIGGER TR_AI_CLIENTE AFTER INSERT ON CLIENTE FOR EACH ROW 
BEGIN
	INSERT INTO BACKUP_CLIENTE VALUES(DEFAULT,NEW.IDCLIENTE,'',NEW.NOME,'0000/00/0000',NEW.DT_NASCIMENTO,'',NEW.CPF,'',NEW.CIDADE,'',NEW.ESTADO,'INSERIDO', NOW() );
END $$

DELIMITER ;

CREATE VIEW alteracoes AS SELECT * FROM BACKUP_CLIENTE ORDER BY DATA_MODIFY;
INSERT INTO CLIENTE VALUES (DEFAULT,'LEO','2000-04-04','123123123','FLORIPA','SC');
UPDATE CLIENTE SET NOME = 'JURANDI' WHERE IDCLIENTE = 1;
DELETE FROM CLIENTE WHERE IDCLIENTE = 1;
SELECT * FROM CLIENTE;
SELECT * FROM alteracoes where idcliente = 1;
